# These are supported funding model platforms
"direct": # https://donate.stripe.com/eVa8zme8l96j1ig5kk
patreon: # https://www.patreon.com/DAFRAYAL
custom: # https://facebook.com/DAFRAYAL
steam: # https://steamcommunity.com/id/DAFRAYAL
train: # https://medium.com/@DAFRAYAL
form: # https://forms.office.com/r/e1Apuf1dvU
